/**
 * Course model used across the Student Course Portal.
 * Defined once here (HOL 6) instead of using `any`, so every
 * component/service gets compile-time type checking.
 */
export interface Course {
  id: number;
  name: string;
  code: string;
  credits: number;
  gradeStatus: 'passed' | 'failed' | 'pending';
  /** Set client-side when the current student has enrolled in this course. */
  enrolled?: boolean;
}

/** Shape used when creating a new course (id is generated by the server). */
export type NewCourse = Omit<Course, 'id'>;
